# membership_service_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership-service
  template:
    metadata:
      labels:
        app: membership-service
    spec:
      containers:
      - name: membership-service
        image: membership_service:latest
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: membership-service
spec:
  selector:
    app: membership-service
  ports:
    - protocol: TCP
      port: 8046
      targetPort: 5000
  type: NodePort